# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u59d3\u540d'),
        ),
    ]
