# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170813_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='imange',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='\u8bfe\u7a0b\u673a\u6784'),
        ),
    ]
